# Dependencies
markdown:         kramdown

# Setup
title:            Portfolio Julian van Santen
description:      'A portfolio page that contains information about Julian and projects he has done.'
url:              http://julianvansanten.nl
baseurl:          /

author:
  name:           'Julian van Santen'
  url:            https://twitter.com/julianvs

# Custom vars

github:           https://github.com/julianvansanten
twitter:          https://twitter.com/julianvsanten
instagram:        https://instagram.com/julianvansanten
linkedin:         https://www.linkedin.com/in/julian-van-santen-4781621a4/